### ISSUE TITLE
Set up the website and publish release

### ISSUE THREAD

**Issue by olexandr-konovalov** [nathancarter/jupyterviz#1]
For packages hosted on GitHub, we offer some tools which relieve technical burden of making a release and remembering all steps in the right order. First, they automate the procedure; Second, someone who has necessary permissions may be able to publish a release for you. The tools are
- https://github.com/gap-system/ReleaseTools 
- https://github.com/gap-system/GitHubPagesForGAP

and their documentation explains how to set them up.

**Comment by olexandr-konovalov** [comment]
In particular, there will be no need to keep release archives under version control, since they will be stored at https://github.com/nathancarter/jupyter-viz/releases, and there will be no need to keep derived PDF files for GAP manuals, since they will be available on the package website.

**Comment by nathancarter** [comment]
I created the website.

I chose not to use ReleaseTools, because when I tried it, it was too picky about capitalization in package names...I would have had to know this before I named everything.  So I set up a MAINTAINERS.md file that explains how to do a release, including updating the version, docs, tarball, and website.

Is it important for me to also remove the PDF manual from version control?

**Comment by olexandr-konovalov** [comment]
I think the fix with capitalization is easy - I use `LowercaseString` in some package of mine:
```
SourceRepository := rec(
    Type := "git",
    URL := Concatenation( "https://github.com/gap-packages/", LowercaseString(~.PackageName) ),
),
IssueTrackerURL := Concatenation( ~.SourceRepository.URL, "/issues" ),
PackageWWWHome  := Concatenation( "https://gap-packages.github.io/", LowercaseString(~.PackageName) ),
README_URL      := Concatenation( ~.PackageWWWHome, "/README.md" ),
PackageInfoURL  := Concatenation( ~.PackageWWWHome, "/PackageInfo.g" ),
ArchiveURL      := Concatenation( ~.SourceRepository.URL,
                                 "/releases/download/v", ~.Version,
                                 "/", LowercaseString(~.PackageName), "-", ~.Version ),
```
I guess that's what you mean by the pickiness above?

Keeping derived files like PDFs in the repos is not a good practice, unless there are exceptions, but I don't think there is a reasonable exception in this case. First, for the user, the manual (html) will be already available on the package page. Second, each time you will rebuild the manual locally, PDF will change and you will have to deal with that. Also, I suggest to remove release tarballs. 

You can keep such things in gh-pages branch, if you want to make them available, but ReleaseTools handles that in quite a clean way. I'd still suggest to try releaseTOols...

**Comment by nathancarter** [comment]
Turns out I was wrong...it wasn't capitalization, but http vs https.  All set now.  Thanks for the help in my office, too!
