### ISSUE TITLE
Request: html splash

### ISSUE THREAD

**Issue by pedritomelenas** [nathancarter/jupyterviz#4]
If an "html splash were" available, one could use the features offered by this package directly on the terminal. 

As we discussed on slack, an example can be found in the function `DotSplash` of [numericalsgps](https://gap-packages.github.io/numericalsgps/) (see the code in [dot.gi](https://github.com/gap-packages/numericalsgps/blob/a65c12217ce337ed332fa80d3c9de0365a1eb5e8/gap/dot.gi#L23)). 

Thank you very much!
Pedro

**Comment by nathancarter** [comment]
I think that issue #8 will help with this as well, and may even be necessary to do first.  Just taking notes here so I don't lose the information when I get back to this.

**Comment by nathancarter** [comment]
For reference, the GAP code that puts HTML content into a temp file and then opens the system default browser on it, based on the link @pedritomelenas gives above, is this.  (Just posting this here to track what I'm doing, and for anyone else who wants to reference this concept later.)
```gap
html := "<html>...put your content here...</html>";
temp_file := Filename( DirectoryTemporary(), "put-filename-here.html" );
out := OutputTextFile( temp_file, false );
SetPrintFormattingStatus( out, false );  
PrintTo( out, html );  
CloseStream( out );
if ARCH_IS_MAC_OS_X() then
    Exec( "open ", temp_file );
elif ARCH_IS_WINDOWS() then
    Exec( "start ", temp_file );
elif ARCH_IS_UNIX() then
    Exec( "xdg-open ", temp_file );
fi;
```

**Comment by nathancarter** [comment]
Completed in v1.4.0, or more specifically, bbe6a5bda48922b752a3983b45f4672de32f89ee.

**Comment by pedritomelenas** [comment]
great! thanks!
