### ISSUE TITLE
Status of automated tests

### ISSUE THREAD

**Issue by olexandr-konovalov** [nathancarter/jupyterviz#9]
Look for example at https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/497572950 - perhaps that's rather something missing in the test setup, rather than failing tests? Do they run interactively?

**Comment by nathancarter** [comment]
Figured it out.  Will put out v1.5.0 momentarily with the fix.

**Comment by nathancarter** [comment]
Finished this yesterday but forgot to close the issue.  Doing so now.
